Save get
cesandoval/PaintingWithData_Riyadh pull request #248
Opened 2018-09-24 03:15 UTC by ooookai

2018-09-24 03:20 UTC, ooookai commented
I haven't test this function when I log in as an User.

2018-09-24 18:27 UTC, ooookai commented on private/jsx/sidebar/Controls.js
> +                }, 1300)
Since the save function is too faster to trust it is already happened, I set 1.3 secs for loading status.

2018-09-24 18:27 UTC, ooookai commented on views/app.jade
> +        var userSignedIn = #{userSignedIn};
access user sign-in information

2018-09-24 19:27 UTC, cesandoval commented on private/jsx/sidebar/Controls.js
> +                }, 1300)
the function is not autosaving currently

2018-09-24 19:27 UTC, cesandoval commented on views/app.jade
> +        var userSignedIn = #{userSignedIn};
even if you are not logged in, you can still save, which shouldn't be the case!

2018-09-24 19:28 UTC, cesandoval requested changes
Hey! the function looks great! it still does not autosave, and show the save icon even if not logged in

2018-09-25 02:09 UTC, ooookai commented on private/jsx/sidebar/Controls.js
> +                }, 1300)
you want to apply autosaving??

2018-09-25 02:10 UTC, ooookai commented on views/app.jade
> +        var userSignedIn = #{userSignedIn};
what do you mean?

2018-09-25 02:11 UTC, ooookai commented
@cesandoval I need you to test the API function when you log-in, and then i will disable the icon when user not log-in.

2018-09-25 02:13 UTC, cesandoval commented
The API works when I am logged in. It still does not autosave when the map is loaded though.

2018-09-26 05:41 UTC, ooookai commented
OK, I will disable the save button when user isn't logged in. 
I thought you know why I don't want the autosaving function?

2018-09-26 14:04 UTC, cesandoval commented
Ok sounds good! Yeah, I thought you had implemented the autosave function, so I got confused. It's fine not to have the autosave for now, I think instead, we can generate the layer colors in the backend and use those by default. But all of that is future work. 

For the save function, I realized that we are actually sending a `json` response once it is saved in the backend. So we can just wait until that response is sent back, instead of the 1300ms delay?

https://github.com/cesandoval/PaintingWithData_Riyadh/pull/248/commits/77d51d16b2f934a6f378fb7693043a3a82b9559c#diff-762420410ec047d5abd72f91dd312730L22

Let me know when I can merge! or just send a PR.

2018-09-26 16:57 UTC, ooookai commented
1300ms is the additional delay after the response, in order to let user trust the function is working instead of failing

2018-09-26 17:37 UTC, cesandoval commented
ok, cool, sounds good! Once you disable it, when a user is not logged in, we can do a PR!

2018-09-30 13:21 UTC, merged